title: Lauren Johnson
logo: lauren_headshot.png
description: Systems engineer with proven expertise in providing hands-on analytical support to drive operational and financial efficiency. 
theme: jekyll-theme-minimal
