title: Lauren Johnson
title_separator: "-"
logo: lauren_headshot.png
description: I collaborate in Financial and Marketing Operations, Business Development, and as a Systems Analyst.
theme: jekyll-theme-minimal
