title: Lauren Johnson
logo: lauren_headshot.png
description: I take a proactive approach to developing compelling promotional materials and business solutions that effectively showcase products and services to both existing and potential clients.
theme: jekyll-theme-minimal
