title: Lauren Johnson
logo: lauren_headshot.png
description: "I collaborate in Financial and Marketing Operations, and as a Systems Analyst. Using a proactive approach to developing compelling promotional materials or business solutions that effectively showcases products and services to both existing and potential clients."


theme: jekyll-theme-minimal
