title: Lauren Johnson
logo: lauren_headshot.png
description: "I collaborate in Financial and Marketing Operations, Business Development, and as a Systems Analyst. I take a proactive approach to developing compelling promotional materials that effectively showcases products and services to both existing and potential clients."
theme: jekyll-theme-minimal
